### ISSUE TITLE
이벤트 발행 기능 구현

### ISSUE THREAD

**Issue by Danue1** [danuelgov/auth#9]
# 내용

이벤트를 발행하고 스케줄링에 의해 이벤트를 소비할 수 있는 기능.

즉시 처리할 필요가 없는 내용을 위한 장치.
장애 발생 등 정상작동이 되지 않는 상태가 되더라도, 정상작동이 되는 시점에 다시 이벤트를 스케줄링 할 수 있어야 함.

## 할 일

- #3 
   - [x] 회원가입 요청 이벤트 발행.
      - [x] `auth.user.signup.requested` (외부 구독 불가능)
   - [x] 회원가입 완료 이벤트 발행.
      - [x] `auth.user.created`
- #5 
   - [x] 로그인 성공/실패 이벤트 발행.
      - [x] `auth.user.login.success`
      - [x] ~~`auth.user.login.failed`~~ #30 이슈 티켓으로 분리
   - [x] ~~로그인 잠금/해제 이벤트 발행.~~ #32 이슈 티켓으로 분리
      - [x] ~~ `auth.user.login.locked` ~~ #32 이슈 티켓으로 분리
      - [x] ~~`auth.user.login.unlocked` ~~ #32 이슈 티켓으로 분리
- #11 
   - [ ] 로그인-비밀번호 변경 이벤트 발행.
      - [ ] `auth.user.password.changed`
- #12 
   - [ ] 비로그인-비밀번호 변경 이벤트 발행.
      - [ ] `auth.user.password.changed`
- #14 
   - [x] ~~회원 활성화/비활성화 이벤트 발행.~~
      - [x] ~~ `auth.user.activated` ~~
      - [x] ~~ `auth.user.deactivated` ~~
- #15 
   - [x] ~~스케줄링에 의해 회원 탈퇴 완료 처리.~~
   - [x] ~~회원 탈퇴 예약/취소/완료 이벤트 발행.~~ #31 이슈 티켓으로 분리
      - [x] ~~ `auth.user.deletion.reserved` ~~
      - [x] ~~ `auth.user.deletion.cancelled` ~~
      - [x] ~~ `auth.user.deleted` ~~

**Comment by Danue1** [comment]
AWS SQS, Apache Kafka, ... MessageQueue-implementation-agnostic하게 구현하려면 어떻게 해야 할까.
Docker를 통해 Apache Kafka를 별도 컨테이너로 띄운 후 살펴 봐야 할까.

**Comment by Danue1** [comment]
기반 플랫폼이 AWS이니 일단 AWS 종속적으로 구현하자.
AWS SNS로 토픽을 만들고, AWS SQS에서 토픽을 구독하는 구조.
토픽에 메시지를 발행하는 주체는 auth 내 서버이고, 토픽에 발행한 메시지를 구독하는 주체는 crates/auth_event_poster.
crates/auth_event_poster는 각 이벤트에 따라 이메일, SMS 등을 발송함.
